/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package komponen;

import Class.ImageFunction;
import Main.Beranda;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import komponen.formProduk;
import Class.dbConnection;

/**
 *
 * @author User
 */
public class Card extends javax.swing.JPanel {
    private final int id_produk;
    static dbConnection db = new dbConnection();
    private Beranda br;
    private File myImg;
    /**
     * Creates new form Card
     * @param id
     * @param br
     */
  
    public Card(int id_produk, Beranda br) {
        initComponents();
        this.id_produk = id_produk;
        this.br = br;
        setProduk();

    }
    
    public void setProduk(){
        try{
            String sql = "SELECT *, p.gambar as pgambar FROM produk p JOIN kategori k ON p.id_kategori = k.id_kategori WHERE p.id_produk = '"+this.id_produk+"'";
            ResultSet res = db.selectQuery(sql);
            while(res.next()){
                labelProduk.setText(res.getString("nama_produk"));
                labelHarga.setText(res.getString("harga"));
                labelKategori.setText(res.getString("nama_kategori"));
                BufferedImage fileImg = null;
                this.myImg = new File("src/image/Produk/"+res.getString("pgambar"));
                fileImg = ImageIO.read(this.myImg);
                Image dimg = fileImg.getScaledInstance(90, 120,ImageFunction.SCALE_SMOOTH);
                img.setIcon(new javax.swing.ImageIcon(dimg));
                
            }            
        }catch(SQLException|IOException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        labelProduk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nama Produk");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Harga");

        labelHarga.setForeground(new java.awt.Color(0, 0, 0));
        labelHarga.setText("jLabel4");

        buttonEdit.setBackground(new java.awt.Color(0, 0, 255));
        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Kategori");

        labelKategori.setForeground(new java.awt.Color(0, 0, 0));
        labelKategori.setText("jLabel4");

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelProduk.setForeground(new java.awt.Color(0, 0, 0));
        labelProduk.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHarga)
                            .addComponent(labelKategori)
                            .addComponent(labelProduk))
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelProduk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelKategori))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonEdit)
                            .addComponent(buttonHapus)))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus data ini ?", "Delete Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            db.updateQuery("DELETE FROM `produk` WHERE id_produk = '"+id_produk+"'");
            try {
                // TODO add your handling code here:
                
                
                if(myImg != null) myImg.delete();
                this.br.setPanel();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        formProduk fa = new formProduk(this.id_produk, this.br);
        fa.setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelProduk;
    // End of variables declaration//GEN-END:variables
}
